config/routes.rb
Rails.application.routes.draw do

  resources :jobs
  get '/say/jobs'
  get '/say/zomato'
  resources :product_categories
  resources :categories
  resources :products
  resources :products
  namespace :api, defaults: {format: "json"} do 
    namespace :v1 do 
      resources :clients 
    end
  end

  get '/tasks/mark_as_complete'
  get '/tasks/mark_as_incomplete'
  resources :tasks

  devise_for :users, controllers: {registrations: 'registrations'}
  resources :clients
  resources :projects

  get 'say/hello'
  get 'say/clients'
  get 'say/projects'

   root 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

	# by default id is pk
	# model_name_id is the FK (naming Convention)

	has_many :tasks
	belongs_to :client
	belongs_to :user


	# has_many :join_table
	# has_many :associated_table, through: :join_table

	has_many :project_categories
	has_many :categories, through: :project_categories

	validates_length_of :description, minimum: 10

	#custom validation
	#validate :check_status
	validate :check_start_date


	def over_due_tasks 
		self.tasks.where('is_completed = ? AND due_date < ?', false, Date.today).order('due_date ASC')
	end

	def incomplete_tasks
		self.tasks.where('is_completed = ? AND due_date >= ?', false, Date.today).order('due_date DESC')
	end

	def completed_tasks
		self.tasks.where('is_completed = ?', true)
	end

	def self.status_statistics_hash(user)
		data = {}
		data["new"] = user.projects.where('status = ?', 'new').size
		data["on-going"] = user.projects.where('status = ?', 'on-going').size
		data["completed"] = user.projects.where('status = ?', 'completed').size
		return data
	end

	def percentage_completed 
		total_tasks = self.tasks.size 
		completed_tasks = self.tasks.where('is_completed = ?',true).size.to_f
		return ((completed_tasks / total_tasks) * 100).to_i
	end


	private

	def check_status
		if self.status != "new"
			errors.add(:status, "should be new")
		end

	 #errors.add(:status, "should be new") if self.status != "new"
	end

	def check_start_date
		if self.start_date > Date.today + 2.weeks 
			errors.add(:start_date, "Cannot be greater than 2 weeks")
		end

		if self.start_date < Date.today
			errors.add(:start_date, "Cannot be in the past")
		end
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_action :authenticate_user!
	def index
		@projects = current_user.projects
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		@project.user_id = current_user.id
		if @project.save
			redirect_to @project, notice: "Success"
		else
			render action: "new"
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	private
	def project_params
		params[:project].permit(:name, :description, :client_id, :status, :start_date, category_ids: [])
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_js.html.erb
<script>
$(document).ready(function(){
	 var array = <%= raw(Project.all.pluck(:start_date).map! {|s| s.to_s}) %>


		$('input').datepicker({
		    beforeShowDay: function(date){
		        var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
		        return [ array.indexOf(string) == -1 ]
		    }
		});

    $('#taskDueDate').datepicker(
    	{ dateFormat: 'yy-mm-dd',
    		changeMonth: true,
     		changeYear: true,

     	});

     var dateFormat = "mm/dd/yy",
      from = $( "#startDate" )
        .datepicker({
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 3
        })
        .on( "change", function() {
          to.datepicker( "option", "minDate", getDate( this ) );
        }),
      to = $( "#endDate" ).datepicker({
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 3
      })
      .on( "change", function() {
        from.datepicker( "option", "maxDate", getDate( this ) );
      });
 
    function getDate( element ) {
      var date;
      try {
        date = $.datepicker.parseDate( dateFormat, element.value );
      } catch( error ) {
        date = null;
      }
 
      return date;
    }
})

</script>

app/views/projects/index.html.erb
<h3>Listing Projects</h3>
<%= form_tag projects_path, method: :get do %>
<%= label_tag :name %> 
<%= text_field_tag :name %>
<%= submit_tag "Search" %>

<% end %>

<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project %> - <%= project.start_date %> 
		</li>
	<% end %>
</ul>

<%= link_to "Add Project", new_project_path %> or

 <%= link_to "export to excel", projects_path(format: "xls") %>

<h2>Project Status</h2>

<% data = {} 

	 data["new"] = @projects.where('status = ?', "new").size
	 data["on-going"] = @projects.where('status = ?', "on-going").size
	 data["completed"] = @projects.where('status = ?', "completed").size

%>

<%= pie_chart(data) %>

<%= pie_chart(Project.status_statistics_hash(current_user)) %>

<h2>Client Project Weight</h2>

<% data = {}
	@projects.each do |project|
		if data.has_key? project.client.name
			data[project.client.name] += 1
		else
			data[project.client.name] = 1
		end
	end
%>
<%= pie_chart(data) %>

<%# data = {}	

	client_ids = @projects.pluck(:client_id).uniq
	client_ids.each do |id|
		client = Client.find(id) # easy reference for client
		data[client.name] = client.projects.size 
	end

%>
<%# pie_chart(data) %>

<% data = {}	
	current_user.clients.each do |client|
		data[client.name] = client.projects.size 
	end
	
%>
<%= pie_chart(data) %>

app/views/projects/index.xls.erb
<h2>Listing Projects</h2>

<table border="1">
	<thead>
		<tr>
			<th>Name</th>
			<th>Start Date</th>
			<th>Client</th>
			<th>Status</th>
		</tr>
	</thead>

	<tbody>
		<% @projects.each do |project| %>
			<tr>
				<td><%= project.name %></td>
				<td><%= project.start_date %></td>
				<td><%= project.client.name %></td>
				<td><%= project.status %></td>
			</tr>
		<% end %>
	</tbody>
</table>

app/views/projects/new.html.erb
<%= render 'js' %>

<h2>Add Project</h2>

<%= form_for @project do |f| %>


<div class="error" style="color:red">
	<% if @project.errors.any? %>
		<h3>These errors prohibitted the form from being saved: </h3>
		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	<% end %>
</div>

<%= f.label :client_id %><br/>
<%= f.collection_select :client_id, Client.all, :id, :name, prompt: "Select Client"  %><br/>

<%= f.label :name %><br/>
<%= f.text_field :name %><br/>

<%= f.label :description %><br/>
<%= f.text_area :description %><br/>

<%= f.label :status %><br/>
<%= f.select :status, ["new", "on-going", "completed"], prompt: "Select Status" %><br/>

<%= f.label :start_date %><br/>
<%= f.text_field :start_date, id: "startDate" %><br/>

<%= f.label :end_date %><br/>
<%= f.text_field :end_date, id: "endDate" %><br/>

<%= f.label :categories %><br/>
<%= f.collection_check_boxes :category_ids, Category.all, :id, :name %>
<br/>
<%= f.submit %>

<% end %>

app/views/projects/show.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="page-header">
			<h1><%= @project.name %> 
				<small>
					<span class="label label-default"><%= @project.status %></span>
				</small>
			</h1>

				<div class="progress">
				  <div class="progress-bar  progress-bar-success" style="width: <%= @project.percentage_completed %>%;">
				  </div>
				</div>

		</div>
	</div>
</div>

<%# @project.client.name if !@project.client.nil?  %>

<h3>Listing Tasks</h3>

<% data = [] 
	@project.tasks.each do |task|
		data.push([task.title, task.project.start_date, task.due_date]) if task.due_date > @project.start_date
	end
%>

<%= timeline data %>


<h4>Over due Tasks</h4>
<ul>
	<% @project.over_due_tasks.each do |task| %>
		<li><%= task.details %> 

		<%= link_to "Mark As Complete", tasks_mark_as_complete_path(task_id: task.id)  %></li>

	<% end %>
</ul>

<h4>Incomplete Tasks</h4>
<ul>
	<% @project.incomplete_tasks.each do |task| %>
		<li><%= task.details %>
		<%= link_to "Mark As Complete", tasks_mark_as_complete_path(task_id: task.id)  %>
		<%# link_to "mark as complete", "/tasks/mark_as_complete?task_id=#{task.id}" %>

		</li>
	<% end %>
</ul>

<h4>Completed Tasks</h4>
<ul>
	<% @project.completed_tasks.each do |task| %>
		<li><%= task.details %>
		<%= link_to "Mark As incomplete", tasks_mark_as_incomplete_path(task_id: task.id)  %>
	<% end %>
</ul>


<h3>Add Task</h3>

<%= form_for @project.tasks.build do |f| %>

<%= f.label :title %><br/>
<%= f.text_field :title %><br/>

<%= f.label :due_date %><br/>
<%= f.text_field :due_date, id: "taskDueDate" %><br/>

<%= f.label :is_completed %><br/>
<%= f.check_box :is_completed %><br/>

<%= f.hidden_field :project_id, value: @project.id %> 

<%= f.submit %>

<% end %>